spring.application.name=finweb

spring.datasource.url=jdbc:mysql://localhost/finweb
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.dll-auto=validate
spring.flyway.enable=true

api.security.token.secret=${JWT_SECRET:12345}

